# -*- coding: utf-8 -*-
"""XYZ_Fulfillment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QWtYk_k5vuKNTlKiKL2qMBQRLdS72wZC

Importing required necessary Libraries:
"""

!pip install streamlit pandas plotly -q

"""Creating a sample dataset for our project:"""

import pandas as pd

orders = pd.DataFrame({
    "Order ID": [
        "ORD001",
        "ORD002",
        "ORD003",
        "ORD004",
        "ORD005",
        "ORD006",
        "ORD007",
        "ORD008"
    ],

    "Channel": [
        "Amazon",
        "Shopify",
        "Flipkart",
        "Amazon",
        "Shopify",
        "Amazon",
        "Flipkart",
        "Shopify"
    ],

    "Priority": [
        "Yes",
        "No",
        "Yes",
        "No",
        "No",
        "Yes",
        "No",
        "No"
    ],

    "Status": [
        "Processing",
        "Packed",
        "Inventory Issue",
        "Shipped",
        "Picking",
        "Processing",
        "Staged",
        "Delivered"
    ],

    "Product": [
        "Wireless Mouse",
        "Keyboard",
        "USB Cable",
        "Laptop Stand",
        "Wireless Mouse",
        "Keyboard",
        "USB Cable",
        "Laptop Stand"
    ],

    "Quantity": [
        2,
        1,
        3,
        1,
        2,
        1,
        4,
        1
    ],

    "Courier": [
        "Delhivery",
        "BlueDart",
        "DTDC",
        "Delhivery",
        "BlueDart",
        "DTDC",
        "Delhivery",
        "BlueDart"
    ]
})

orders

inventory = pd.DataFrame({
    "SKU": [
        "SKU001",
        "SKU002",
        "SKU003",
        "SKU004"
    ],

    "Product": [
        "Wireless Mouse",
        "Keyboard",
        "USB Cable",
        "Laptop Stand"
    ],

    "Main Warehouse": [
        25,
        8,
        4,
        30
    ],

    "Backup Warehouse": [
        40,
        25,
        50,
        10
    ],

    "Minimum Stock": [
        10,
        15,
        20,
        10
    ]
})

inventory

"""Delevloping required KPI's:"""

total_orders = len(orders)

priority_orders = len(
    orders[orders["Priority"] == "Yes"]
)

inventory_issues = len(
    orders[orders["Status"] == "Inventory Issue"]
)

at_risk_orders = len(
    orders[
        orders["Status"].isin(
            ["Processing", "Picking"]
        )
    ]
)

print("Total Orders:", total_orders)
print("Priority Orders:", priority_orders)
print("Inventory Issues:", inventory_issues)
print("At Risk Orders:", at_risk_orders)

"""Now the Visualization comes into role:

Orders by Status:
"""

import plotly.express as px

status_count = orders["Status"].value_counts().reset_index()

status_count.columns = ["Status", "Orders"]

fig = px.bar(
    status_count,
    x="Status",
    y="Orders",
    color="Status",
    title="Orders by Fulfillment Status",
    text="Orders"
)

fig.update_layout(
    xaxis_title="Order Status",
    yaxis_title="Number of Orders",
    showlegend=False
)

fig.show()

"""Priority vs Normal Orders:

"""

priority_count = orders["Priority"].value_counts().reset_index()

priority_count.columns = ["Priority", "Orders"]

fig = px.pie(
    priority_count,
    names="Priority",
    values="Orders",
    title="Priority vs Normal Orders"
)

fig.show()

"""Orders by Channel:"""

channel_count = orders["Channel"].value_counts().reset_index()

channel_count.columns = ["Channel", "Orders"]

fig = px.bar(
    channel_count,
    x="Channel",
    y="Orders",
    color="Channel",
    title="Orders by Sales Channel",
    text="Orders"
)

fig.update_layout(
    xaxis_title="Sales Channel",
    yaxis_title="Number of Orders",
    showlegend=False
)

fig.show()

"""Orders by Courier:"""

courier_count = orders["Courier"].value_counts().reset_index()

courier_count.columns = ["Courier", "Orders"]

fig = px.bar(
    courier_count,
    x="Courier",
    y="Orders",
    color="Courier",
    title="Orders by Courier",
    text="Orders"
)

fig.update_layout(
    xaxis_title="Courier",
    yaxis_title="Number of Orders",
    showlegend=False
)

fig.show()

"""Inventory in Main vs Backup Warehouse:"""

inventory_chart = inventory[
    ["Product", "Main Warehouse", "Backup Warehouse"]
]

inventory_long = inventory_chart.melt(
    id_vars="Product",
    var_name="Warehouse",
    value_name="Stock"
)

fig = px.bar(
    inventory_long,
    x="Product",
    y="Stock",
    color="Warehouse",
    barmode="group",
    title="Inventory by Warehouse"
)

fig.update_layout(
    xaxis_title="Product",
    yaxis_title="Stock Quantity"
)

fig.show()

"""Low Stock Products:"""

inventory["Stock Status"] = inventory.apply(
    lambda row: "Low Stock"
    if row["Main Warehouse"] <= row["Minimum Stock"]
    else "Healthy",
    axis=1
)

inventory_status = inventory[
    ["Product", "Main Warehouse", "Minimum Stock", "Stock Status"]
]

inventory_status

fig = px.bar(
    inventory_status,
    x="Product",
    y=["Main Warehouse", "Minimum Stock"],
    barmode="group",
    title="Current Stock vs Minimum Stock"
)

fig.update_layout(
    xaxis_title="Product",
    yaxis_title="Quantity"
)

fig.show()

""" Orders Requiring Attention:"""

issues = orders[
    (orders["Priority"] == "Yes") |
    (orders["Status"] == "Inventory Issue") |
    (orders["Status"] == "Picking")
]

issues

issue_count = issues["Status"].value_counts().reset_index()

issue_count.columns = ["Issue", "Orders"]

fig = px.bar(
    issue_count,
    x="Issue",
    y="Orders",
    color="Issue",
    title="Orders Requiring Attention",
    text="Orders"
)

fig.update_layout(
    xaxis_title="Issue / Status",
    yaxis_title="Number of Orders",
    showlegend=False
)

fig.show()

"""Creating APP:"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# 
# # Page settings
# st.set_page_config(
#     page_title="XYZ Fulfillment",
#     page_icon="📦",
#     layout="wide"
# )
# 
# # Title
# st.title("📦 XYZ Fulfillment Dashboard")
# 
# st.write(
#     "Monitor orders, inventory and fulfillment issues."
# )
# 
# st.divider()
# 
# 
# # -----------------------------
# # ORDER DATA
# # -----------------------------
# 
# orders = pd.DataFrame({
#     "Order ID": [
#         "ORD001", "ORD002", "ORD003", "ORD004",
#         "ORD005", "ORD006", "ORD007", "ORD008"
#     ],
# 
#     "Channel": [
#         "Amazon", "Shopify", "Flipkart", "Amazon",
#         "Shopify", "Amazon", "Flipkart", "Shopify"
#     ],
# 
#     "Priority": [
#         "Yes", "No", "Yes", "No",
#         "No", "Yes", "No", "No"
#     ],
# 
#     "Status": [
#         "Processing", "Packed", "Inventory Issue",
#         "Shipped", "Picking", "Processing",
#         "Staged", "Delivered"
#     ],
# 
#     "Product": [
#         "Wireless Mouse",
#         "Keyboard",
#         "USB Cable",
#         "Laptop Stand",
#         "Wireless Mouse",
#         "Keyboard",
#         "USB Cable",
#         "Laptop Stand"
#     ],
# 
#     "Quantity": [
#         2, 1, 3, 1,
#         2, 1, 4, 1
#     ],
# 
#     "Courier": [
#         "Delhivery", "BlueDart", "DTDC", "Delhivery",
#         "BlueDart", "DTDC", "Delhivery", "BlueDart"
#     ]
# })
# 
# 
# # -----------------------------
# # INVENTORY DATA
# # -----------------------------
# 
# inventory = pd.DataFrame({
#     "SKU": [
#         "SKU001",
#         "SKU002",
#         "SKU003",
#         "SKU004"
#     ],
# 
#     "Product": [
#         "Wireless Mouse",
#         "Keyboard",
#         "USB Cable",
#         "Laptop Stand"
#     ],
# 
#     "Main Warehouse": [
#         25, 8, 4, 30
#     ],
# 
#     "Backup Warehouse": [
#         40, 25, 50, 10
#     ],
# 
#     "Minimum Stock": [
#         10, 15, 20, 10
#     ]
# })
# 
# 
# # -----------------------------
# # KPI CALCULATIONS
# # -----------------------------
# 
# total_orders = len(orders)
# 
# priority_orders = len(
#     orders[orders["Priority"] == "Yes"]
# )
# 
# inventory_issues = len(
#     orders[orders["Status"] == "Inventory Issue"]
# )
# 
# at_risk_orders = len(
#     orders[
#         orders["Status"].isin(
#             ["Processing", "Picking"]
#         )
#     ]
# )
# 
# 
# # -----------------------------
# # KPI CARDS
# # -----------------------------
# 
# st.subheader("Today's Overview")
# 
# col1, col2, col3, col4 = st.columns(4)
# 
# col1.metric(
#     "Total Orders",
#     total_orders
# )
# 
# col2.metric(
#     "🔴 Priority Orders",
#     priority_orders
# )
# 
# col3.metric(
#     "⚠️ Inventory Issues",
#     inventory_issues
# )
# 
# col4.metric(
#     "⏰ At Risk Orders",
#     at_risk_orders
# )
# 
# 
# st.divider()
# 
# 
# # -----------------------------
# # ORDERS BY STATUS
# # -----------------------------
# 
# status_count = (
#     orders["Status"]
#     .value_counts()
#     .reset_index()
# )
# 
# status_count.columns = [
#     "Status",
#     "Orders"
# ]
# 
# fig1 = px.bar(
#     status_count,
#     x="Status",
#     y="Orders",
#     color="Status",
#     text="Orders",
#     title="Orders by Fulfillment Status"
# )
# 
# fig1.update_layout(
#     showlegend=False
# )
# 
# 
# # -----------------------------
# # PRIORITY VS NORMAL
# # -----------------------------
# 
# priority_count = (
#     orders["Priority"]
#     .value_counts()
#     .reset_index()
# )
# 
# priority_count.columns = [
#     "Priority",
#     "Orders"
# ]
# 
# fig2 = px.pie(
#     priority_count,
#     names="Priority",
#     values="Orders",
#     title="Priority vs Normal Orders"
# )
# 
# 
# # -----------------------------
# # DISPLAY CHARTS
# # -----------------------------
# 
# col1, col2 = st.columns(2)
# 
# with col1:
#     st.plotly_chart(
#         fig1,
#         use_container_width=True
#     )
# 
# with col2:
#     st.plotly_chart(
#         fig2,
#         use_container_width=True
#     )
# 
# 
# # -----------------------------
# # INVENTORY CHART
# # -----------------------------
# 
# st.subheader("📦 Inventory Overview")
# 
# inventory_long = inventory[
#     [
#         "Product",
#         "Main Warehouse",
#         "Backup Warehouse"
#     ]
# ].melt(
#     id_vars="Product",
#     var_name="Warehouse",
#     value_name="Stock"
# )
# 
# fig3 = px.bar(
#     inventory_long,
#     x="Product",
#     y="Stock",
#     color="Warehouse",
#     barmode="group",
#     title="Inventory by Warehouse"
# )
# 
# st.plotly_chart(
#     fig3,
#     use_container_width=True
# )
# 
# 
# # -----------------------------
# # ORDER FILTER
# # -----------------------------
# 
# st.subheader("📋 Order Management")
# 
# status_filter = st.selectbox(
#     "Filter Orders by Status",
#     ["All"] + list(orders["Status"].unique())
# )
# 
# if status_filter == "All":
#     filtered_orders = orders
# else:
#     filtered_orders = orders[
#         orders["Status"] == status_filter
#     ]
# 
# st.dataframe(
#     filtered_orders,
#     use_container_width=True,
#     hide_index=True
# )
# 
# 
# # -----------------------------
# # INVENTORY TABLE
# # -----------------------------
# 
# st.subheader("📦 Inventory Status")
# 
# inventory["Stock Status"] = inventory.apply(
#     lambda row:
#     "⚠️ Low Stock"
#     if row["Main Warehouse"] <= row["Minimum Stock"]
#     else "✅ Healthy",
#     axis=1
# )
# 
# st.dataframe(
#     inventory,
#     use_container_width=True,
#     hide_index=True
# )
# 
# 
# # -----------------------------
# # ORDERS REQUIRING ATTENTION
# # -----------------------------
# 
# st.subheader("⚠️ Orders Requiring Attention")
# 
# issues = orders[
#     (orders["Priority"] == "Yes") |
#     (orders["Status"] == "Inventory Issue") |
#     (orders["Status"] == "Picking")
# ]
# 
# st.dataframe(
#     issues,
#     use_container_width=True,
#     hide_index=True
# )
# 
# 
# st.divider()
# 
# st.caption(
#     "XYZ Fulfillment | Data Analyst Take-Home Project"
# )
#

!ls

!pkill -f streamlit

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb

!streamlit run app.py > /content/streamlit.log 2>&1 &

!cloudflared tunnel --url http://localhost:8501

"""Now just click on the link having trycloudflare.com in the end, this will take us in our application.

If have any trouble having the link please click on this link: This is the application Link I have created:                                       https://artwork-pichunter-connected-ira.trycloudflare.com/
"""